sudo: required
services:
  - redis-server

addons:
  postgresql: "9.6"

language: python

python:
  - "3.6"
  - "3.7-dev"

before_script:
  - psql -c 'create database test_dvhb_hybrid;' -U postgres
  - psql test_dvhb_hybrid -c 'create table test(id serial, text text NOT NULL, data jsonb);' -U postgres

install:
  - pip install -U pip setuptools pipenv==2018.5.18
  - pipenv install -d --skip-lock

script: pytest

notifications:
  email:
    on_success: change
    on_failure: always
