# Config file for automatic testing at travis-ci.org

sudo: required
services:
  - redis-server

addons:
  postgresql: "9.5"

language: python

python: 3.5

before_script:
  - psql -c 'create database test_dvhb_hybrid;' -U postgres
  - psql test_dvhb_hybrid -c 'create table test(id serial, text text, data jsonb);' -U postgres

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_success: change
    on_failure: always
