swagger: '2.0'

paths:
  '':
    $name: hybrid.files:image:upload
    put:
      operationId: image_upload
      tags:
        - files
      summary: Upload new image
      description:
        Takes form with file.
        Create an entry in db and save file.

      consumes:
        - multipart/form-data

      parameters:

        - name: file
          in: formData
          description: Файл
          required: true
          type: file

      produces:
        - application/json

      responses:
        400:
          description: Bad request
          schema:
            type: object
        403:
          description: Need permissions
          schema:
            type: object
        200:
          description: File was saved
          schema:
            type: object
            properties:
              uuid:
                type: string

  '/{uuid}/{processor}_{width:\d+}x{height:\d+}.{ext}':
    $name: hybrid.files:image:processor
    head:
      $handler: dvhb_hybrid.aviews.http200
      tags:
        - files
    get:
      operationId: photo_handler
      tags:
        - files
      summary: URL image
      description: Create URL for image

      parameters:

        - &param_uuid
          name: uuid
          in: path
          description: Image id
          required: true
          type: string

        - &param_processor
          name: processor
          in: path
          description: processor for image
          required: true
          type: string
          enum:
            - size

        - &param_width
          name: width
          in: path
          description: Width
          required: true
          type: integer
          format: int32
          minimum: 2
          maximum: 3000

        - &param_height
          name: height
          in: path
          description: Height
          required: true
          type: integer
          format: int32
          minimum: 2
          maximum: 3000

        - &param_ext
          name: ext
          in: path
          description: File ext
          required: true
          type: string

      responses: &get_response
        404:
          description: Not found
          schema:
            type: object
        200:
          description: File
          schema:
            type: object

  '/{uuid}/{processor}_{width:\d+}x{height:\d+}_2x.{ext}':
    $name: hybrid.files:image_2x:processor
    head:
      $handler: dvhb_hybrid.aviews.http200
      tags:
        - files
    get:
      operationId: photo_handler
      tags:
        - files
      summary: URL of image
      description: Create URL for iamge

      parameters:
        - *param_uuid
        - *param_processor
        - *param_width
        - *param_height
        - *param_ext

      responses: *get_response

  '/{uuid}/origin_2x.{ext}':
    head:
      $handler: dvhb_hybrid.aviews.http200
      tags:
        - files
    get:
      operationId: photo_handler
      tags:
        - files
      summary: URL
      description: Creates URL for image

      parameters:
        - *param_uuid
        - *param_ext

      responses: *get_response

  '/{uuid}/origin.{ext}':
    $name: hybrid.files:image:origin
    head:
      $handler: dvhb_hybrid.aviews.http200
      tags:
        - files
    get:
      operationId: photo_handler
      tags:
        - files
      summary: URL
      description: Create URL for image

      parameters:
        - *param_uuid
        - *param_ext

      responses: *get_response
