swagger: '2.0'

paths:
  /change/password:
    $name: user:change:password
    put:
      operationId: user_request_change_password
      tags:
        - user
      summary: Change password
      description: Change user password

      consumes:
        - application/x-www-form-urlencoded

      parameters:
      - name: email
        in: formData
        description: User email address
        required: true
        type: string
        format: email

      produces:
        - application/json

      responses:
        200:
          description: OK
        400:
          description: Invalid email
        401:
          description: email not found
        403:
          description: User disabled

    post:
      operationId: user_change_password_by_request
      tags:
        - user
      summary: Change password
      description: Change user password

      security:
      - UserSecurity: []

      consumes:
        - application/x-www-form-urlencoded

      parameters:
        - name: new_password
          in: formData
          description: New password
          required: true
          type: string

      produces:
        - application/json
